//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        public int GameID { get; set; }
        public string GameName { get; set; }
        public string GameDesc { get; set; }
        public Nullable<int> Total_scores { get; set; }
        public Nullable<int> Num_of_spectators { get; set; }
        public string Winning_team { get; set; }
        public int TeamA { get; set; }
        public int tracker_fk { get; set; }
        public int TeamB { get; set; }
        public Nullable<int> TeamAScore { get; set; }
        public Nullable<int> TeamBScore { get; set; }
    
        public virtual Tracker Tracker { get; set; }
        public virtual Tracker Tracker1 { get; set; }
        public virtual Team Team { get; set; }
        public virtual Team Team1 { get; set; }
    }
}
