//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResultsView
    {
        public Nullable<int> GameID { get; set; }
        public System.DateTime GameDate { get; set; }
        public int TeamAScore { get; set; }
        public int TeamBScore { get; set; }
        public int Spectators { get; set; }
        public int PointsAgainst { get; set; }
        public int TotalScore { get; set; }
        public string Winner { get; set; }
        public string TeamA { get; set; }
        public string TeamB { get; set; }
    }
}
